# -*- coding: utf-8 -*-
"""PDF_Ingestion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RGgId2KYbws9xSiSHxGppoXHuh7Td9p

# Install, Imports, Re-used Functions
"""

#pip install --upgrade pymupdf

import pymupdf

# Document extraction from pdf into a doc for processing
doc1 = pymupdf.open("/content/(ebook-pdf) - Cooking - Copycat recipes.pdf")

# Initial glance at metadata gives basic insight into document format
doc1.metadata

doc1.page_count

# Table of contents can be very helpful for parsing/chunking/namespacing by topic
table_of_contents = doc1.get_toc()

# Get a look at the first 10 entries of the table of contents
for item in table_of_contents[:20]:
  print(item)

page = doc1[24]

print(page.get_text()[:500])

recipes = []

for entry in table_of_contents:
  level, title, page = entry

  recipes.append(
      {
          "title": title.strip(),
          "start_page": page
      }
  )

# Take a look at the first entries of the recipes list
recipes[:5]

# Slice off the entries that aren't correlated to an actual recipe
recipes = recipes[3:]
recipes[:5]

# Take a look at the last entries of the recipes list
recipes[-5:]

# Find out how many chunks we are going to make from this
num_recipes = len(recipes)
num_recipes

for i in range(num_recipes):
  if i < num_recipes - 1:
    recipes[i]["end_page"] = recipes[i + 1]["start_page"] - 1

  else:
    recipes[i]["end_page"] = doc1.page_count

recipes[:3]

recipes[-3:]

recipe = recipes[-2]
recipe

# Adjust the start page for 0-indexing, but not the end page for the exclusive
# nature of the range function when we extract text.
start_page = recipe['start_page'] - 1
end_page = recipe['end_page']

recipe_text = (
    doc1[start_page].get_text() + doc1[end_page].get_text()
)
recipe_text[:1000]